/*
 **********************************************************************************************************************
 *
 * draupnir-lib
 * Copyright (C) 2025-2026 Ivan Odinets <i_odinets@protonmail.com>
 *
 * This file is part of draupnir-lib
 *
 * draupnir-lib is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * draupnir-lib is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with draupnir-lib; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

#ifndef MESSAGEGROUP_H
#define MESSAGEGROUP_H

#include <atomic>

#include "draupnir/utils/integer_wrapper.h"

namespace Draupnir::Logging
{

/*! @class MessageGroupId draupnir/logging/core/MessageGroupId.h
 *  @ingroup Logging
 *  @brief Identifies a logical group of related logged messages.
 *
 *  @details This class is a lightweight wrapper around an integer identifier. It is used by @ref Draupnir::Logging::Logger to
 *           associate several log messages with the same logical operation or batch.
 *
 *           Grouped messages may be temporarily accumulated and processed later when the group is flushed or ended. Grouped
 *           messages may be temporarily accumulated by Logger and delivered when the corresponding group is flushed or ended.
 *
 *           This class is copyable, comparable, and hashable, making it usable as a key in standard and Qt containers such
 *           as `std::map`, `std::unordered_map`, `QMap`, `QHash`, etc.
 *
 * @see Draupnir::Logging::Logger */

class MessageGroupId final : public draupnir::utils::integer_wrapper<uint64_t, MessageGroupId>
{
    using _Base = draupnir::utils::integer_wrapper<uint64_t, MessageGroupId>;

public:
    /*! @brief Generates a new unique message group identifier.
     *  @return Identifier unique among values previously generated by this function, assuming the internal counter has not
     *          overflowed.
     * @note The generated value is unique within the current process. */
    [[nodiscard]] static MessageGroupId generate() noexcept {
        static std::atomic<uint64_t> counter{1};
        return MessageGroupId{counter.fetch_add(1, std::memory_order_relaxed)};
    }

    using _Base::integer_wrapper;
    using _Base::operator=;

    /*! @brief Returns the internal numeric ID of the group.
     *  @return Integer ID of the group. */
    [[nodiscard]] constexpr auto id() const noexcept { return this->value(); }
};

} // namespace Draupnir::Logging

namespace std {
    template <>
    struct hash<Draupnir::Logging::MessageGroupId> {
        std::size_t operator()(const Draupnir::Logging::MessageGroupId& group) const noexcept {
            return std::hash<Draupnir::Logging::MessageGroupId::underlying_type>{}(group.value());
        }
    };
}

#include <QHash>

inline uint qHash(const Draupnir::Logging::MessageGroupId& key, uint seed = 0) noexcept {
    return ::qHash(key.value(), seed);
}

#endif // MESSAGEGROUP_H
